# Generated by Django 5.1.5 on 2025-03-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
