# Generated by Django 5.1.5 on 2025-03-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_end_attendance_booking_start_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_attendance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_attendance',
        ),
        migrations.AddField(
            model_name='booking',
            name='attended',
            field=models.CharField(choices=[('AB', 'Absent'), ('ST', 'Start'), ('EN', 'End'), ('AT', 'Attended')], default='AB', max_length=2),
        ),
    ]
