# Generated by Django 5.1.5 on 2025-03-17 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_booking_end_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('badge_description', models.CharField(max_length=100)),
                ('badge_image', models.ImageField(blank=True, upload_to='badges_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('badge_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.badge')),
            ],
        ),
    ]
