# Generated by Django 5.1.5 on 2025-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_badge_award'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('sign_up', 'Can sign up for events'), ('badges', 'Can be awarded badges and can access the badges page'))},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=23),
        ),
    ]
